role_questions = {
    'developer': [
        "An API endpoint you designed is experiencing high traffic and is becoming a bottleneck. How would you redesign it for scalability?",
        "A file upload blocks other operations. How would you handle multiple uploads efficiently?",
        "How would you design a distributed cache system for a high-traffic web application?",
        "Describe your process for conducting a code review and what you look for.",
        "A service is using an excessive amount of memory and is frequently garbage-collecting. How do you identify the cause and optimize its performance?",
        "You need to implement a feature that requires a new database table. What are the key considerations for table schema design?",
        "How would you handle user authentication and authorization in a microservices architecture?",
        "A production bug is reported that only occurs under specific, rare conditions. How do you approach debugging this issue?",
        "What's the difference between optimistic and pessimistic locking, and when would you use each?",
        "How would you secure a REST API against common threats like CSRF and injection attacks?",
        "A build is failing in a CI/CD pipeline due to a dependency issue. How do you debug and resolve it?",
        "You need to migrate data from an old database to a new one with a different schema. What is your strategy for a smooth migration?",
        "How do you ensure that your code is maintainable and scalable?",
        "What are the trade-offs of using a NoSQL database versus a relational database?",
        "How would you design a logging and monitoring system for a complex application?",
        "A critical function is slow and is impacting user experience. How would you profile it and find the bottleneck?",
        "Describe a time you refactored a large, complex piece of code.",
        "How would you use a message queue (like RabbitMQ or SQS) to decouple services?",
        "What are the benefits and drawbacks of using a front-end framework like React or Angular?",
        "You need to implement a feature that requires real-time updates to the UI. What technology would you use (e.g., WebSockets, Server-Sent Events)?",
        "How do you handle secrets and sensitive data in your code and configuration files?",
        "Describe your experience with containerization (e.g., Docker) and how it helps in development and deployment.",
        "What is the SOLID principle, and how do you apply it in your code?",
        "How would you design an architecture that is resilient to component failures?",
        "An external service you rely on is down. How would you implement a fallback mechanism to prevent your application from failing?",
        "Describe a scenario where you would use a design pattern like Observer or Singleton.",
        "How do you ensure that your code is portable across different environments (e.g., dev, staging, production)?",
        "What are the key considerations for building a highly available system?",
        "How would you optimize the load time of a web page with many images and scripts?",
        "Describe your approach to test-driven development (TDD).",
        "A complex feature needs to be built by multiple developers. How do you break down the work and manage the dependencies?",
        "How would you use a content delivery network (CDN) to improve application performance?",
        "Your team is struggling with frequent merge conflicts. What strategies would you propose to improve the workflow?",
        "How would you approach a problem of optimizing a large, complex SQL query?",
        "Describe a time you had to debug a difficult memory leak in a production environment.",
        "How would you design a system to handle file uploads of varying sizes efficiently without blocking the main application thread?",
        "An API endpoint you designed is experiencing high traffic and is becoming a bottleneck. How would you redesign it for scalability?",
        "What are the trade-offs between monolithic and microservices architectures?",
        "How would you handle errors and retries when calling external APIs?",
        "Describe a time when you had to deal with a security vulnerability in your code. How did you handle it?",
        "How do you keep up with the latest technologies and best practices in your field?",
        "You need to implement a real-time chat feature. What technologies and architectural patterns would you use?",
        "How do you ensure that your application is accessible to users with disabilities?",
        "A crucial service has a high error rate. How would you implement a circuit breaker pattern to prevent cascading failures?",
        "What is the difference between synchronous and asynchronous operations, and when would you use each?",
        "How would you design a system for handling a large volume of background jobs?",
        "Describe a time you had to learn a new programming language or framework for a project.",
        "You have a database table with millions of rows. How would you ensure queries remain fast and efficient?",
        "How would you approach a refactoring project on a legacy codebase with no tests?",
        "What are the benefits of using a container orchestration tool like Kubernetes?",
        "How do you ensure that your code is robust and handles all possible edge cases?",
        "A user report indicates that a feature is not working as expected. How do you approach reproducing and fixing the bug?",
        "What is the difference between a push and a pull based approach for data processing?",
        "How would you handle a large amount of sensitive data in a system?",
        "You need to implement a feature that requires a new database and a new microservice. How would you coordinate the development and deployment?",
        "Describe a time when you had to choose between a quick fix and a more robust, long-term solution.",
        "How do you write unit tests for a function that has external dependencies?",
        "What are the benefits of using an ORM (Object-Relational Mapping) framework?",
        "How would you design a highly available and fault-tolerant system?",
        "A new requirement for a feature is vague and undefined. How do you clarify it with the product manager?",
        "How would you use a message broker to handle events in a distributed system?",
        "Describe a time when you had to resolve a production issue under pressure.",
        "What are the key elements of a good API design?",
        "How would you design a system to handle rate limiting for an API?",
        "What are the pros and cons of using a monorepo vs. a polyrepo?",
        "How do you ensure that your code is well-documented and easy for others to understand?",
        "Describe a time you had to work with a legacy system that was poorly documented.",
        "How would you design a system to handle large data imports from external sources?",
        "What is the difference between horizontal and vertical scaling, and when would you use each?",
        "How do you manage secrets in your CI/CD pipeline?",
        "A stakeholder requests a feature that is technically challenging and may delay the project. How do you communicate the risks?",
        "How would you handle state management in a complex front-end application?",
        "Describe a time you used an asynchronous task queue (e.g., Celery) to improve application performance.",
        "What are the benefits of using a serverless architecture?",
        "How would you design a system to handle real-time user activity tracking and analytics?",
        "A team member introduced a bug in a critical service. How would you handle the situation?",
        "What are the key considerations for building a multi-tenant application?",
        "How would you use feature flags to manage the rollout of new features?",
        "Describe a time you had to optimize a front-end application for a mobile device.",
        "What is the difference between authentication and authorization?",
        "How would you design a system to handle database migrations in a team environment?",
        "What is your approach to writing clean, readable, and maintainable code?",
        "How would you use observability to monitor the health of your services?",
        "A new feature has been requested that will require a significant change to the database schema. How would you handle the deployment?",
        "What are the benefits and drawbacks of using GraphQL instead of a REST API?",
        "How do you manage and reduce technical debt in a project?",
        "A crucial database has become corrupt. How would you handle the recovery process?",
        "What is the difference between a service mesh and an API gateway?",
        "How would you approach building a highly scalable search engine?",
        "Describe a time you had to perform an emergency hotfix in production.",
        "How do you ensure code quality and consistency across a large team?",
        "A critical service is failing silently, and you need to add more robust error handling. How do you approach this?",
        "What is the difference between a monolith and a distributed monolith?",
        "How would you design a system that can process data from various sources with different schemas?",
        "Describe a time you had to work with an unfamiliar codebase. What was your process?",
        "What are the key considerations for building a secure login system?",
        "How would you use a caching layer to improve performance and reduce database load?",
        "Describe a time you had to refactor a system to use a new technology.",
        "How would you design a system to handle large-scale data ingestion and processing?",
        "What is the difference between a load balancer and a reverse proxy?",
        "A new requirement will impact multiple teams. How do you coordinate the changes and dependencies?",
        "How do you handle session management in a distributed application?"
    ],
    'designer': [
        "You're designing an app for a new social media platform. What's your strategy for user onboarding and first-time user experience?",
        "A client wants a website that sells personalized artisanal coffee blends. How would you design the product customization flow?",
        "You need to redesign a popular e-commerce checkout page to reduce cart abandonment. What are your key focus areas?",
        "Design a user interface for a smart home thermostat. What are the key controls and how would you make them intuitive?",
        "A client has requested a mobile app for booking doctor's appointments. How would you handle the calendar view and appointment selection?",
        "You're tasked with creating an information dashboard for a city's public transportation system. How do you prioritize and display real-time data?",
        "Design an accessible website for a government service, ensuring it's usable for people with visual impairments and other disabilities?",
        "A company wants to gamify their fitness app to increase user engagement. What features would you design and what metrics would you track?",
        "You need to design a user flow for a password reset. How do you balance security with user convenience?",
        "A B2B SaaS company wants to redesign its analytics dashboard. How would you handle the visualization of complex data for a non-technical audience?",
        "How would you design a dark mode for an existing mobile application? What are the key considerations?",
        "You're designing a feature for a news app that allows users to save articles for later. How would you make this experience seamless?",
        "A new banking app needs to make its financial reports easy to understand for everyday users. How would you visualize the data?",
        "Design a system for a new social network that allows users to create and manage 'circles' of friends with varying levels of privacy?",
        "How would you approach designing a mobile app for a museum that helps visitors navigate and learn about exhibits?",
        "You're designing a food delivery app. How do you handle the menu browsing experience when a restaurant has hundreds of items?",
        "A client wants to create an app that helps people manage their personal budget. How do you design the data input and spending tracking features?",
        "Design a landing page for a new AI-powered photo editing software. What's the key message and call-to-action?",
        "You need to create an interface for a medical device that monitors a patient's vital signs. How do you ensure the design is clear and error-free?",
        "How would you design a feedback system for a corporate intranet, encouraging employees to submit suggestions and report issues?",
        "Design a mobile app for a public library that allows users to check out books, manage their account, and find new titles?",
        "You're building a feature that allows users to create and share short-form videos. How do you design the editing tools to be both powerful and simple?",
        "A client wants to redesign their booking platform for flights and hotels. How would you handle the complex search and filter options?",
        "How would you design a rating and review system for an online marketplace? What are the key elements to consider?",
        "Design a user flow for a 'buy now, pay later' feature in an e-commerce app. How do you communicate the payment schedule clearly?",
        "You need to design an interface for a car's infotainment system. How do you balance functionality with driver safety?",
        "A new educational app needs to track a student's progress and provide personalized recommendations. How would you design this feature?",
        "How would you design a digital art portfolio website for a creative professional? What features are essential?",
        "Design a user interface for a virtual reality (VR) application. What are the unique challenges and considerations?",
        "You're designing a new feature for a project management tool. How would you visualize task dependencies and project timelines?",
        "A client wants to create an app that connects users with local tutors. How would you design the search and booking process?",
        "How would you design a digital loyalty card system for a chain of coffee shops?",
        "You need to design an onboarding flow for a complex data analysis tool. How do you guide new users without overwhelming them?",
        "Design a system for a peer-to-peer lending app. How would you build trust and transparency between borrowers and lenders?",
        "A company wants to design a new employee benefits portal. How would you make complex information easy to find and understand?",
        "How would you design a feature that allows users to create custom playlists on a music streaming service?",
        "You're designing a landing page for a subscription box service. How do you convey value and entice visitors to subscribe?",
        "A new social media platform wants to design a system for content moderation. How would you approach this?",
        "How would you design a user interface for a kiosk that helps people navigate a large shopping mall?",
        "You need to design an app that helps people track their water intake. How would you make this experience engaging?",
        "Design a feature for a travel app that allows users to collaborate on planning a trip with friends?",
        "How would you design a system for a job-seeking platform that matches candidates with relevant job listings?",
        "A company wants to create an app for remote team collaboration. How would you design the communication and task management features?",
        "You're designing a new feature for a photo-sharing app that allows users to create and join 'albums' with friends. What are the key interactions?",
        "How would you design a user interface for a video conferencing tool, optimizing for both desktop and mobile?",
        "Design a system for a community forum where users can post questions and get answers. How do you handle reputation and trust?",
        "A client wants a website for a local non-profit organization. How would you design it to encourage donations and volunteer sign-ups?",
        "How would you design a user interface for a smart refrigerator that tracks food inventory and suggests recipes?",
        "You need to design a system for a dating app that allows users to filter potential matches. How do you balance user control with the discovery of new people?",
        "Design a user flow for a subscription cancellation process. How do you balance business needs with a good user experience?",
        "A new fitness app needs to provide workout plans tailored to a user's goals. How would you design the personalization and progression features?",
        "How would you design a landing page for an API service, targeting developers and businesses?",
        "You're designing an app for a new restaurant that allows customers to order food in advance for pickup. How would you handle the ordering process and payment?",
        "How would you design a system for a language learning app that tracks a user's progress and adapts to their learning style?",
        "A client wants to create an app that helps people track and manage their personal finances. How would you design the budgeting and expense categorization features?",
        "Design a user interface for a smart washing machine with multiple settings and cycles. How do you make it easy to use?",
        "You're designing a new feature for a recipe app that allows users to create a weekly meal plan. How would you design this?",
        "How would you design a user interface for a complex data visualization tool for a scientific audience?",
        "A client wants to design an app for a charity that helps people find volunteer opportunities. How do you design the search and sign-up flow?",
        "How would you design a new feature for a note-taking app that allows users to collaborate on notes in real-time?",
        "You're designing a system for a crowdfunding platform. How do you design the project submission and review process?",
        "How would you design an application for a mental health service that provides anonymous support? How do you ensure a sense of safety and trust?",
        "A company wants to redesign its corporate website. How would you design the 'About Us' and 'Team' sections to build trust with potential clients?",
        "How would you design a user interface for a new cryptocurrency trading platform, targeting both beginners and experienced traders?",
        "You need to design a system for a travel-sharing app where users can review and recommend places. How would you handle user-generated content and trust?",
        "How would you design a new feature for a news website that summarizes long articles using AI?",
        "A client wants to create an app that helps people track and manage their personal goals. How would you design the goal-setting and progress-tracking features?",
        "How would you design a user interface for a hospital's patient record system, ensuring data is secure and easy to access for medical staff?",
        "You're designing an app that helps people find and join local sports teams. How would you handle the team discovery and communication features?",
        "How would you design a system for an online learning platform that offers courses from various institutions?",
        "A company wants to create an app that helps people find and book home cleaning services. How would you design the booking and payment process?",
        "How would you design a feature for a music streaming app that allows users to create and share 'mixtapes' of songs with a personal message?",
        "You're designing a system for a real estate platform. How do you design the property search, comparison, and tour booking features?",
        "How would you design a new feature for a social media app that allows users to create and join private groups?",
        "A client wants to design a website for a new online magazine. How would you design the article layouts and navigation to encourage reading?",
        "How would you design a user interface for a smart vacuum cleaner's companion app, allowing users to schedule cleanings and view maps of their home?",
        "You're designing a new feature for an e-commerce platform that allows users to compare different products side-by-side. How would you design this?",
        "How would you design a system for a new social network that allows users to create short-form text posts and threads?",
        "A company wants to design an app that helps people track their daily habits. How would you design the habit tracking and motivation features?",
        "How would you design a user interface for a system that helps people manage and pay their bills?",
        "You need to design a new feature for a weather app that provides hyper-local, real-time weather alerts. How would you make the alerts non-intrusive?",
        "How would you design a system for an online community where users can host and join virtual events?",
        "A client wants to design an app that helps people with public speaking. How would you design the practice and feedback features?",
        "How would you design a user interface for a smart home security system, allowing users to arm/disarm and view camera feeds?",
        "You're designing a new feature for a food delivery app that allows users to tip the delivery person after the delivery is complete. What are the key interactions?",
        "How would you design a system for a digital portfolio website for a creative agency, showcasing their case studies and projects?",
        "A company wants to design an app that helps people find and rent cars. How would you design the search, booking, and pickup/drop-off process?",
        "How would you design a new feature for a messaging app that allows users to send disappearing messages?",
        "You need to design a system for an online platform that connects freelance writers with clients. How would you handle the project bidding and payment process?",
        "How would you design a user interface for a new podcast app, making it easy for users to discover new shows and manage their subscriptions?",
        "A client wants to design an app that helps people find and book pet-sitting services. How would you design the search and booking flow?",
        "How would you design a new feature for a social media app that allows users to create polls and quizzes?",
        "You're designing a system for an online store that sells personalized gifts. How would you design the product customization and preview features?",
        "How would you design a user interface for a telehealth app that connects patients with doctors via video call?",
        "A company wants to design an app that helps people find and reserve parking spots. How would you handle the map view and payment process?",
        "How would you design a new feature for a streaming service that allows users to create a 'watch party' with friends?",
        "You need to design a system for an online platform that helps people manage their personal and professional networks?",
        "How would you design a user interface for a stock trading app, targeting beginners who are new to investing?",
        "A client wants to design an app that helps people learn a new musical instrument. How would you design the lesson and practice features?",
        "How would you design a system for a new social platform that allows users to create and share 'moments' based on their location?"
    ],

    'analyst': [
        "A client wants to understand why their website's conversion rate has dropped by 15% in the last month. How would you approach this investigation?",
        "You are given a dataset of customer purchase history. What analysis would you perform to identify the most valuable customer segments?",
        "A company is considering launching a new product. What data would you need to collect and analyze to forecast its potential sales?",
        "You're analyzing sales data and notice a significant spike on a specific day. How would you investigate the cause of this anomaly?",
        "A marketing team wants to know the ROI of their latest campaign. What metrics would you use to measure its effectiveness?",
        "You are tasked with analyzing customer churn. What are the key indicators you'd look for, and what recommendations would you make?",
        "How would you use A/B testing to determine if a change to a website's call-to-action button improves click-through rate?",
        "A business has a large amount of unstructured customer feedback. How would you analyze this data to identify key themes and sentiment?",
        "You're presented with a large, messy dataset with missing values and inconsistencies. What's your process for data cleaning and preparation?",
        "A stakeholder asks you to analyze the performance of a new feature. What metrics would you track, and how would you present the results?",
        "How would you conduct a market basket analysis to find out which products are frequently bought together?",
        "A company wants to optimize its pricing strategy. What data would you analyze, and what models would you build to help with this decision?",
        "You are given a dataset with customer demographics and purchase behavior. How would you use this to create a customer segmentation model?",
        "A manager wants to know if there's a correlation between employee satisfaction and productivity. How would you analyze the available data?",
        "How would you use a time series analysis to forecast future sales for a seasonal product?",
        "A client wants to understand the lifetime value (LTV) of their customers. How would you calculate this, and what insights would you provide?",
        "You're analyzing website traffic data. How would you identify the most effective channels for acquiring new users?",
        "A business has multiple data sources that don't align. How would you reconcile the data to create a single, reliable source of truth?",
        "How would you use a funnel analysis to identify where users are dropping off during the conversion process?",
        "A stakeholder wants to know the impact of a recent pricing change on sales. How would you analyze this using a control group?",
        "You are tasked with identifying the key drivers of customer satisfaction. What data would you analyze, and what statistical methods would you use?",
        "A company wants to personalize the customer experience on its website. What data would you analyze to create a recommendation engine?",
        "How would you use SQL to analyze a database of customer orders to find the average order value per month?",
        "A manager wants a report on key business metrics. What dashboards and visualizations would you create to present this data effectively?",
        "You're analyzing sales data and notice a particular sales region is underperforming. How would you investigate the root cause?",
        "How would you use regression analysis to determine the relationship between advertising spend and revenue?",
        "A client wants to understand the effectiveness of their email marketing campaigns. What metrics would you analyze, and how would you segment the data?",
        "You have a large amount of server log data. How would you analyze it to identify potential security vulnerabilities or performance issues?",
        "A business wants to optimize its inventory management. What data would you analyze to forecast demand for a specific product?",
        "How would you use clustering to group similar products based on their features and sales data?",
        "A stakeholder asks for a report on employee retention. What data would you need, and what key insights would you provide?",
        "How would you use a decision tree to predict whether a customer will churn?",
        "You're analyzing the performance of a mobile app. How would you identify the most engaging features and the areas where users are getting stuck?",
        "A company wants to identify which features of their product are most used. How would you analyze user behavior data to answer this?",
        "How would you use a cohort analysis to track the behavior of a group of customers over time?",
        "A manager wants to know if there's a statistically significant difference in sales between two different marketing campaigns. How would you test this?",
        "You are tasked with analyzing the cost-effectiveness of different customer support channels. What data would you need?",
        "How would you use a geospatial analysis to determine the best locations for opening new retail stores?",
        "A business wants to understand the sentiment of online reviews for their product. How would you use natural language processing (NLP) to analyze this?",
        "How would you conduct a root cause analysis for a sudden drop in website traffic?",
        "You're given a dataset of website clicks and user sessions. How would you calculate the most popular user paths?",
        "A stakeholder wants to know the average time it takes for a customer support ticket to be resolved. How would you analyze this data?",
        "How would you use a sensitivity analysis to determine how changes in key variables would affect a business model?",
        "You're analyzing product return data. How would you identify the most common reasons for returns and make recommendations?",
        "A company wants to optimize its ad spend. How would you use data to determine the most cost-effective platforms?",
        "How would you use a simulation to model the potential impact of a new pricing strategy?",
        "You are tasked with analyzing social media engagement for a brand. What metrics would you track, and what insights would you provide?",
        "How would you use a heat map to visualize user interactions on a website?",
        "A manager wants to know the impact of a new feature on user engagement. How would you measure this using event tracking?",
        "You're analyzing call center data. How would you identify the most common reasons for customer calls?",
        "How would you use a 'what-if' analysis to model different business scenarios?",
        "A client wants to understand the demographics of their most loyal customers. How would you analyze the data to answer this?",
        "You're analyzing customer survey data. How would you identify the most significant drivers of customer satisfaction?",
        "How would you use a pivot table to summarize and analyze sales data by product and region?",
        "A business wants to optimize its shipping costs. What data would you analyze to find the most efficient shipping routes?",
        "How would you use a statistical process control chart to monitor a business process and identify when it's out of control?",
        "You're analyzing email unsubscribe data. How would you identify the key reasons why users are unsubscribing?",
        "A company wants to understand the impact of a promotion on sales. How would you analyze this using a pre- and post-analysis?",
        "How would you use a sentiment analysis to analyze customer feedback from various online sources?",
        "You're given a dataset of website traffic and bounce rates. How would you identify which pages have the highest bounce rates and make recommendations for improvement?",
        "A stakeholder wants to know the correlation between customer support response time and customer satisfaction. How would you analyze this?",
        "How would you use a Monte Carlo simulation to forecast project completion time?",
        "You are tasked with analyzing the performance of a new marketing channel. What metrics would you track, and how would you compare it to existing channels?",
        "A company wants to understand the demographics of the people who interact with their social media posts. How would you analyze this data?",
        "How would you use a survival analysis to predict customer churn over time?",
        "You're analyzing data on user sign-ups and conversions. How would you identify the key friction points in the sign-up process?",
        "A manager wants to know the most common reasons for product returns. How would you analyze the data to create a report?",
        "How would you use a principal component analysis (PCA) to reduce the dimensionality of a large dataset?",
        "You're analyzing customer data and notice a group of customers who have been inactive for a long time. How would you use this to create a re-engagement campaign?",
        "A business wants to understand the impact of a new product launch on sales of their other products. How would you analyze this?",
        "How would you use a funnel analysis to identify where users are dropping off during the app download and installation process?",
        "You are tasked with analyzing the performance of a new website design. How would you measure its impact on user engagement and conversions?",
        "A stakeholder wants to know if there's a relationship between the time of day and website traffic. How would you analyze this?",
        "How would you use a machine learning model to predict customer behavior based on their past actions?",
        "You're analyzing data on customer reviews. How would you identify the key themes and common complaints?",
        "A company wants to optimize its email send times. What data would you analyze to find the best time to send emails for maximum open rates?",
        "How would you use a text mining analysis to identify common keywords and phrases in customer support tickets?",
        "You're analyzing website search data. How would you identify the most popular search terms and the searches that result in no results?",
        "A business wants to understand the impact of a new website banner on sales. How would you analyze this using a split test?",
        "How would you use a time series analysis to identify seasonal trends in sales data?",
        "You are tasked with analyzing data on employee sick days. How would you identify any patterns or correlations?",
        "A stakeholder wants to know the most popular product categories on their e-commerce site. How would you analyze this?",
        "How would you use a geospatial analysis to identify which regions have the highest customer concentration?",
        "You're analyzing data on user subscriptions and cancellations. How would you identify the key reasons for cancellations?",
        "A company wants to understand the impact of a discount on sales volume. How would you analyze this?",
        "How would you use a cluster analysis to group customers based on their purchase behavior?",
        "You're analyzing data on website page load times. How would you identify which pages are the slowest and make recommendations for improvement?",
        "A stakeholder wants to know the most common path users take through a website before making a purchase. How would you analyze this?",
        "How would you use a regression analysis to determine the factors that influence customer satisfaction?",
        "You're analyzing data on customer complaints. How would you identify the key themes and prioritize which issues to address first?",
        "A company wants to understand the impact of a new feature on user retention. How would you analyze this?",
        "How would you use a time series analysis to forecast the number of customer support tickets for the next month?",
        "You are tasked with analyzing the effectiveness of different social media platforms for driving traffic to a website. How would you do this?",
        "A stakeholder wants to know the average time it takes for a new user to make their first purchase. How would you analyze this?",
        "How would you use a 'what-if' analysis to model the impact of a competitor's pricing change on your sales?",
        "You're analyzing data on customer support agent performance. How would you identify the top-performing agents?",
        "A company wants to understand the relationship between website visits and sales. How would you analyze this?",
        "How would you use a sentiment analysis to analyze customer reviews and identify areas for product improvement?",
        "You're analyzing data on website search queries. How would you identify the most popular keywords that lead to a conversion?",
        "A stakeholder wants to know the most common reason why a user signs up for a free trial but doesn't convert to a paying customer. How would you analyze this?",
        ],
    'tester': [
    "A client reports that the 'Add to Cart' button is not working on a product page. What's your first step to investigate this issue?",
    "You're testing a new login feature. How would you approach testing the password reset functionality?",
    "The application's response time is noticeably slow during peak hours. How would you identify the root cause of this performance issue?",
    "A new bug is reported that only occurs in a specific browser (e.g., Firefox) and not others. How would you test and document this?",
    "You're testing a new file upload feature. How would you handle testing with various file types, sizes, and names?",
    "A critical bug is discovered in production right after a new release. What's your process for validating the fix and ensuring it doesn't cause a regression?",
    "How would you test a mobile application's behavior when the user loses internet connectivity?",
    "You're tasked with testing a feature that involves real-time data updates (e.g., a live chat). What's your strategy?",
    "A user reports that a form is not saving their information correctly. How would you test for potential data validation errors?",
    "You need to test the security of a new user registration form. What are some of the tests you would perform to check for vulnerabilities?",
    "How would you design test cases for a new search functionality that has multiple filters and sorting options?",
    "A new feature for a social media app allows users to create and share stories. What are some of the negative test scenarios you'd consider?",
    "You're performing a regression test on an application with a new build. How do you decide which tests to run?",
    "The development team made a change to the database schema. How would you test the impact of this change on the application's functionality?",
    "You're testing an e-commerce website. How would you test the functionality of a coupon code during the checkout process?",
    "A bug is reported where the UI appears distorted on certain screen resolutions. How would you verify and document this?",
    "How would you test the performance of a web page that contains many high-resolution images and videos?",
    "You need to test a new feature that sends email notifications to users. How would you verify that the emails are sent correctly and contain the right information?",
    "How would you test a mobile app's behavior when it's interrupted by a phone call or a text message?",
    "You're testing a new analytics dashboard. How would you verify that the data being displayed is accurate and up-to-date?",
    "A client reports that the 'Forgot Password' link is not working on the login page. What are the key test cases you would create to investigate?",
    "How would you test the compatibility of a web application across different operating systems (Windows, macOS, Linux)?",
    "You're testing a feature that involves a user's location (e.g., a map app). How would you simulate and test different locations?",
    "A new bug is reported where the application crashes on startup. How do you approach debugging and reporting this?",
    "How would you test a web application's behavior when a user is using an outdated browser version?",
    "You need to test a new feature that involves a credit card payment. How would you handle testing different payment scenarios (e.g., failed payments, invalid cards)?",
    "A client reports that a specific report is generating incorrect data. How would you test the data integrity and accuracy of the report?",
    "How would you test the usability of a new user onboarding flow? What are the key metrics you'd focus on?",
    "You're testing a feature that allows users to upload profile pictures. What are the test cases for handling image cropping and resizing?",
    "A bug is reported where the application's performance degrades significantly when there are a large number of users. How would you test this?",
    "How would you test the accessibility of a website to ensure it's usable for people with visual or motor impairments?",
    "You need to test the performance of an API endpoint that handles a large volume of requests. What tools and methods would you use?",
    "A client reports that a specific feature is not working as expected in their local time zone. How would you test for localization and time zone issues?",
    "How would you test the functionality of a real-time notification system (e.g., push notifications on a mobile app)?",
    "You're testing a feature that allows users to import data from a CSV file. What are the key test cases for handling malformed or invalid data?",
    "A new bug is reported that only occurs on a specific type of device (e.g., an older Android phone). How would you approach testing on that device?",
    "How would you test the security of a user's session management, ensuring that they are properly logged out after a period of inactivity?",
    "You need to test a new feature for a video streaming service that allows users to fast-forward and rewind. How would you test for smooth playback?",
    "How would you test the functionality of a chatbot that handles customer service inquiries?",
    "A bug is reported where an application's UI elements overlap on certain screen sizes. How would you test for responsiveness?",
    "You're testing a new feature for a ride-sharing app that allows users to schedule a ride in advance. What are the key test cases?",
    "How would you test the functionality of a form that uses a CAPTCHA to prevent bots?",
    "A client reports that a specific feature is causing the application to consume an excessive amount of battery on mobile devices. How would you test this?",
    "How would you test a new feature for a note-taking app that allows users to share notes with others?",
    "You need to test the performance of a search engine's indexing and search speed. What's your strategy?",
    "A bug is reported where a user's profile picture is not loading correctly. How would you test this issue?",
    "How would you test the functionality of a new feature for an e-commerce site that allows users to create a 'wishlist'?",
    "You're testing a feature that involves a user's camera and microphone. What are the key test cases for handling permissions and device availability?",
    "A client reports that a specific report is slow to generate. How would you test the performance of the report generation process?",
    "How would you test the functionality of a feature that allows users to save and load their progress in a game?",
    "You're testing a new feature for a calendar app that allows users to set recurring events. What are the key test cases?",
    "A bug is reported where a user's email address is not being validated correctly on a registration form. How would you test this?",
    "How would you test the functionality of a feature that allows users to send and receive files in a messaging app?",
    "You need to test the performance of a large data import process. What are the key metrics you'd focus on?",
    "A client reports that a specific feature is not working as expected when using a keyboard for navigation instead of a mouse. How would you test this?",
    "How would you test the security of an API endpoint to ensure it's not vulnerable to common attacks like SQL injection?",
    "You're testing a new feature for a ride-sharing app that allows drivers to receive live updates on new ride requests. What's your strategy?",
    "A bug is reported where the application's UI is not consistent across different pages. How would you test for design and style guide violations?",
    "How would you test a new feature that allows users to sign in using their social media accounts (e.g., Google, Facebook)?",
    "You need to test the functionality of a new feature for a banking app that allows users to transfer money between accounts. What are the key test cases?",
    "A client reports that a specific feature is not working as expected when the user's account is suspended. How would you test for different user account states?",
    "How would you test a new feature that allows users to leave comments on articles on a news website?",
    "You're testing the performance of a web application under heavy load. What tools would you use to simulate multiple users?",
    "A bug is reported where a user is unable to delete their account. How would you test the 'delete account' functionality?",
    "How would you test a new feature that allows users to create and manage their profiles on a social media app?",
    "You need to test the functionality of a feature that allows users to share a file via a public link. How would you test for access control and security?",
    "A client reports that the application is crashing when they upload a corrupted file. How would you test for file integrity and error handling?",
    "How would you test the functionality of a new feature for a video editing app that allows users to trim and merge video clips?",
    "You're testing a new feature for an e-commerce site that allows users to review and rate products. How would you test for fraudulent reviews?",
    "A bug is reported where a specific UI element is not clickable on a mobile device. How would you test for tap target size and spacing?",
    "How would you test the functionality of a new feature that allows users to chat with a customer support agent in real-time?",
    "You need to test the performance of a mobile app's startup time. What are the key metrics you'd focus on?",
    "A client reports that a specific feature is not working as expected when the device's battery is low. How would you test for this?",
    "How would you test the functionality of a feature that allows users to add and manage their credit cards in a payment app?",
    "You're testing a new feature that allows users to create and manage their own groups on a social network. What are the key test cases?",
    "A bug is reported where the application's UI is not adapting correctly to different orientations (e.g., portrait vs. landscape). How would you test for this?",
    "How would you test the functionality of a new feature for a podcast app that allows users to download episodes for offline listening?",
    "You need to test the security of a user's login session when they are using a public Wi-Fi network. How would you approach this?",
    "A client reports that a specific feature is not working as expected in a location with a weak network signal. How would you test for network instability?",
    "How would you test the functionality of a new feature for a mapping app that allows users to report traffic incidents?",
    "You're testing a new feature for a streaming service that allows users to create their own playlists. What are the key test cases for adding and removing songs?",
    "A bug is reported where the application's UI is not consistent with the brand's color palette. How would you test for visual design adherence?",
    "How would you test the functionality of a new feature for a job-seeking app that allows users to apply for jobs with one click?",
    "You need to test the performance of a new feature that involves a complex calculation. What's your strategy for verifying the results are accurate?",
    "A client reports that a specific feature is causing the application to freeze or become unresponsive. How would you test for memory leaks?",
    "How would you test a new feature for a food delivery app that allows users to track their order in real-time?",
    "You're testing the security of a new feature that involves a user's personal information. How would you test for data privacy?",
    "A bug is reported where the application's UI is not rendering correctly on a specific model of a mobile device. How would you test for device-specific issues?",
    "How would you test the functionality of a new feature for a language learning app that provides real-time feedback on pronunciation?",
    "You need to test the performance of a new feature that involves a large number of database queries. What's your strategy for optimization?",
    "A client reports that a specific feature is not working as expected when a user's account has special characters in their name. How would you test for this?",
    "How would you test the functionality of a new feature for a dating app that allows users to 'like' or 'dislike' other users?",
    "You're testing a new feature for an e-commerce site that allows users to leave comments on products. How would you test for content moderation?",
    "A bug is reported where the application's UI elements are not aligned correctly on a specific browser. How would you test for cross-browser compatibility?",
    "How would you test the functionality of a new feature for a social media app that allows users to 'tag' other users in photos?",
    "You need to test the performance of a mobile app's battery consumption. How would you measure this?",
    "A client reports that a specific feature is not working as expected when the user's device's date and time are set incorrectly. How would you test for this?",
    "How would you test the functionality of a new feature for a travel app that allows users to create a custom itinerary?",
    "You're testing a new feature for a banking app that allows users to set up recurring payments. What are the key test cases for handling failures?",
    "A bug is reported where a user is unable to submit a form with a large amount of text. How would you test for input limits and validation?"
],
       
    'manager' : [
    "A high-performing team member is showing signs of burnout. How do you approach this situation?",
    "Two of your key team members have a personality conflict that is affecting the team's productivity. How do you resolve this?",
    "A team member consistently misses deadlines, but their work quality is high. How do you address this?",
    "One of your direct reports has asked for a significant salary increase, but your budget is limited. How do you handle this negotiation?",
    "How do you handle a situation where a team member is resistant to a new company policy or process?",
    "You need to give negative feedback to a team member who is not meeting expectations. How do you prepare for and conduct this conversation?",
    "A team member is underperforming and has shown no signs of improvement despite previous feedback. What's your next step?",
    "How do you manage a remote team to ensure they stay engaged and collaborative?",
    "A team member is constantly complaining about their workload, but you know they have the capacity. How do you address this perception issue?",
    "How do you handle a situation where a team member is a subject matter expert but is not sharing their knowledge with the rest of the team?",
    "You have a new team member joining from a different background. How do you ensure their successful integration?",
    "A team member has made a significant mistake that has impacted the project. How do you handle the situation with the client and the team member?",
    "How do you motivate a team that has just completed a long, difficult project and is experiencing fatigue?",
    "A team member has received a job offer from another company. They are a critical part of the team. How do you handle this?",
    "How do you handle a situation where a team member is a 'lone wolf' and prefers to work independently, which is impacting team collaboration?",
    "A project is behind schedule due to a technical roadblock. How do you get it back on track?",
    "The scope of a project keeps changing due to client requests. How do you manage scope creep and set realistic expectations?",
    "You have a tight deadline for a critical project, but your team's workload is already at capacity. How do you prioritize and allocate resources?",
    "A key stakeholder is unhappy with the project's progress and direction. How do you address their concerns?",
    "How do you manage a project with multiple dependencies on other teams that are also facing their own challenges?",
    "You've been asked to take over a project that is in a state of chaos. What's your first step?",
    "A project's initial requirements are vague and undefined. How do you work with the stakeholders to clarify them?",
    "A critical team member is unexpectedly out for an extended period. How do you manage the project's continuity?",
    "How do you handle a situation where a project's budget is being exceeded, and you need to ask for more funding?",
    "A project is at risk of failure. How do you conduct a 'post-mortem' to learn from the mistakes and prevent them in the future?",
    "How do you communicate a major company change (e.g., a new strategy, a layoff) to your team?",
    "You've been asked to lead a new initiative that is outside your area of expertise. How do you approach this?",
    "How do you foster a culture of innovation and continuous improvement within your team?",
    "A new competitor has entered the market. How do you lead your team to adapt and respond to this new threat?",
    "How do you get buy-in from your team on a new, unpopular decision from upper management?",
    "A stakeholder is pressuring you to cut corners to meet a deadline. How do you balance quality with speed?",
    "How do you empower your team members to take ownership of their work and make decisions independently?",
    "You have a new, difficult stakeholder who is highly critical of your team's work. How do you build a positive working relationship with them?",
    "How do you lead a team through a period of high uncertainty or organizational change?",
    "How do you foster a culture of psychological safety where team members feel comfortable speaking up about mistakes or concerns?",
    "You need a resource from another department to complete your project, but their manager is uncooperative. How do you handle this?",
    "How do you facilitate a productive meeting with multiple stakeholders from different departments who have conflicting priorities?",
    "A new feature requires collaboration between your team and the marketing team, but they have different timelines and goals. How do you align them?",
    "How do you handle a situation where another team is consistently delivering late, which is impacting your team's progress?",
    "You need to present a complex technical solution to a non-technical audience. How do you tailor your communication to be effective?",
    "Two team members have a disagreement over the best technical approach to a problem. How do you mediate and help them reach a consensus?",
    "A team member is in a conflict with a client. How do you de-escalate the situation and find a resolution?",
    "How do you handle a situation where a team member is challenging your authority in a meeting?",
    "A team member is upset about a decision that was made without their input. How do you address their feelings and move forward?",
    "How do you handle a disagreement with your own manager on a key strategic decision?",
    "A team member has expressed interest in a different role within the company. How do you support their career development?",
    "How do you create a clear career path for your team members?",
    "How do you handle a team member who is not receptive to coaching or feedback?",
    "You need to conduct a performance review for a team member. How do you ensure it is fair, objective, and constructive?",
    "A team member has the technical skills but lacks 'soft skills' like communication. How do you help them develop in this area?",
    "A critical service has gone down in production. How do you manage the response, communicate with stakeholders, and lead the team to a solution?",
    "A major client is threatening to leave due to a bug in your product. How do you handle the situation?",
    "How do you manage your team's stress and anxiety during a crisis?",
    "You've discovered a serious security vulnerability in your product. How do you manage the communication and the fix?",
    "A competitor has launched a product that is significantly better than yours. How do you lead your team in this new reality?",
    "You have been given a new project with an insufficient budget. How do you manage this constraint?",
    "How do you handle a situation where you need to hire, but the company has frozen all new hires?",
    "You have a limited number of licenses for a critical tool. How do you prioritize which team members get access?",
    "How do you manage a team's time and energy to prevent burnout when resources are scarce?",
    "A key vendor you rely on is experiencing a service outage. How do you manage your project's dependencies?",
    "How do you encourage your team to think outside the box and propose new ideas?",
    "A team member has a great idea but lacks the data to support it. How do you help them validate their concept?",
    "How do you manage a team that is afraid to take risks for fear of failure?",
    "You're faced with a complex problem that no one on your team has encountered before. How do you approach it?",
    "How do you foster a culture where it's safe for team members to admit they don't know something?",
    "Your team is moving to a new development methodology (e.g., Agile). How do you manage the transition?",
    "How do you communicate the 'why' behind a major change to your team to get their buy-in?",
    "A new tool or technology is being introduced that will change your team's workflow. How do you manage the training and adoption?",
    "How do you handle a situation where a team member is actively sabotaging a new process?",
    "How do you manage the emotional side of change, such as fear and uncertainty, within your team?",
    "How do you manage the expectations of a high-level stakeholder who is constantly changing their mind?",
    "A stakeholder is unhappy with a project's outcome, even though it met all the initial requirements. How do you handle this?",
    "How do you build trust with stakeholders who are skeptical of your team's abilities?",
    "You need to decline a request from a powerful stakeholder. How do you communicate this without damaging the relationship?",
    "How do you keep stakeholders informed of a project's progress without overwhelming them with unnecessary details?",
    "A team member has reported a violation of the company's code of conduct. How do you investigate this with discretion and fairness?",
    "How do you handle a situation where a client is asking your team to do something that you believe is unethical?",
    "A team member has been caught taking credit for another person's work. How do you address this?",
    "How do you foster a culture of integrity where team members feel comfortable reporting mistakes or issues?",
    "You've discovered that a team member is leaking confidential information. How do you handle this situation?",
    "How do you delegate a complex task to a junior team member in a way that sets them up for success?",
    "A team member is reluctant to take on a new responsibility. How do you empower them to do so?",
    "How do you delegate effectively without micromanaging your team?",
    "A team member has a great idea but lacks the confidence to take the lead. How do you mentor them?",
    "How do you handle a situation where a delegated task is not completed to the required standard?",
    "You need to hire a new team member. What are the key qualities you look for in a candidate?",
    "How do you design an interview process that accurately assesses a candidate's skills and cultural fit?",
    "A top candidate has a competing job offer. How do you convince them to join your team?",
    "How do you handle a situation where a new hire is not performing as expected during their probationary period?",
    "What's your strategy for onboarding a new team member to ensure they are productive and engaged from day one?",
    "How do you create an environment where team members feel comfortable giving you feedback?",
    "How do you handle a situation where a team member is not listening to your instructions?",
    "A team member has a bad habit of interrupting others in meetings. How do you address this?",
    "How do you communicate a project's failure to your team without demoralizing them?",
    "You need to provide a project update to a busy executive. How do you make your communication concise and effective?",
    "How do you manage your own time and priorities when you have competing demands from multiple stakeholders?",
    "A team member has asked for advice on their career path. How do you mentor them?",
    "How do you stay updated on industry trends and best practices in management?",
    "How do you handle a situation where you've made a mistake as a manager? How do you own it?",
    "What is your approach to continuous learning and personal development as a manager?",
    ],
    'general' : [
    "Explain your role in a recent software project and how you contributed.",
    "Describe a challenging technical problem you solved and your approach.",
    "How do you stay updated with new technologies and trends?",
    "Describe a time you debugged a complex issue under pressure.",
    "How do you document work for colleagues and future reference?",
    "Explain a situation where you had to learn a new technology quickly.",
    "Describe how you handle tight deadlines or high-pressure situations.",
    "How do you collaborate effectively with team members?",
    "What version control or project management tools have you used?",
    "How do you ensure the quality and accuracy of your deliverables?",
    "Describe a project where you had to work with a difficult stakeholder.",
    "Tell me about a time you had a disagreement with a team member and how you resolved it.",
    "How do you prioritize your tasks when you have multiple competing deadlines?",
    "Describe a time you received constructive criticism and how you responded.",
    "How do you handle a situation where a project is failing or has a major setback?",
    "Explain a time you had to pivot your approach mid-project.",
    "What is your process for giving and receiving feedback?",
    "How do you handle a situation where a client's requirements are vague or change frequently?",
    "Describe a time you had to mentor a junior team member.",
    "How do you manage your time and stay organized on a daily basis?",
    "Tell me about a time you had to present a complex idea to a non-technical audience.",
    "What's a time you went above and beyond for a project?",
    "Describe a situation where you had to make a decision with limited information.",
    "How do you ensure you are meeting your professional development goals?",
    "Explain a time you identified a potential risk in a project and how you mitigated it.",
    "How do you approach a new project or a new problem you haven't seen before?",
    "Describe a time you automated a repetitive task to improve efficiency.",
    "How do you handle a situation where a team member is not pulling their weight?",
    "Tell me about a time you had to deal with a difficult customer or client.",
    "How do you stay motivated when working on a long-term project?",
    "Describe a time you had to lead a small team or group.",
    "How do you handle a situation where a project is behind schedule?",
    "Explain a time you had to persuade someone to see your point of view.",
    "What is your approach to handling multiple projects at once?",
    "Describe a time you failed at something and what you learned from it.",
    "How do you build a good working relationship with your colleagues?",
    "Tell me about a time you had to work with a new team or new people.",
    "How do you ensure that your work is scalable and maintainable?",
    "Describe a time you had to make a compromise to achieve a goal.",
    "How do you handle a situation where you don't agree with your manager's decision?",
    "Explain a time you had to deliver bad news to a stakeholder.",
    "How do you ensure that you are continuously improving your skills?",
    "Describe a time you had to simplify a complex process.",
    "How do you handle a situation where you are given a task with an unrealistic deadline?",
    "Tell me about a time you had to deal with a crisis or an emergency at work.",
    "What is your process for conducting research for a project?",
    "How do you handle a situation where you are facing a lack of resources?",
    "Describe a time you had to deal with a conflict between two team members.",
    "How do you maintain a good work-life balance?",
    "Explain a time you had to manage a project's budget.",
    "How do you ensure that your code is well-tested and bug-free?",
    "Describe a time you had to work on a project with a very tight budget.",
    "How do you handle a situation where a project's scope keeps expanding?",
    "Tell me about a time you had to work on a legacy system or an old codebase.",
    "How do you ensure that your team is meeting its goals and objectives?",
    "Describe a time you had to make a difficult decision that impacted your team.",
    "How do you handle a situation where you are given a task you don't want to do?",
    "Tell me about a time you had to build a strong relationship with a new client.",
    "How do you stay calm and focused under pressure?",
    "Describe a time you had to work on a project with a diverse team.",
    "How do you ensure that your work is aligned with the company's goals?",
    "Tell me about a time you had to lead a meeting or a presentation.",
    "How do you handle a situation where a team member makes a mistake?",
    "Describe a time you had to learn a new tool or software for a project.",
    "How do you ensure that your work is well-organized and easy for others to understand?",
    "Tell me about a time you had to solve a problem with no clear solution.",
    "How do you handle a situation where you are feeling overwhelmed at work?",
    "Describe a time you had to manage a project with a large number of stakeholders.",
    "How do you handle a situation where you receive conflicting instructions from two different people?",
    "Tell me about a time you had to build a consensus among a group of people.",
    "How do you handle a situation where a team member is unhappy with their role?",
    "Describe a time you had to resolve a production issue under pressure.",
    "How do you ensure that you are continuously learning and growing?",
    "Tell me about a time you had to work on a project with a very short timeline.",
    "How do you handle a situation where you are not getting the support you need from your manager?",
    "Describe a time you had to deal with a security vulnerability in a project.",
    "How do you ensure that your team is communicating effectively?",
    "Tell me about a time you had to present a new idea to a team or a group.",
    "How do you handle a situation where a team member is not a good fit for the project?",
    "Describe a time you had to negotiate with a client or a vendor.",
    "How do you handle a situation where a project is at risk of being canceled?",
    "Tell me about a time you had to deal with a difficult or unreasonable request.",
    "How do you ensure that your work is robust and handles all possible edge cases?",
    "Describe a time you had to refactor a large piece of code or a system.",
    "How do you handle a situation where a team member is underperforming?",
    "Tell me about a time you had to work with a legacy system that was poorly documented.",
    "How do you handle a situation where a project's requirements are unclear?",
    "Describe a time you had to make a tough decision under pressure.",
    "How do you ensure that your work is scalable and efficient?",
    "Tell me about a time you had to manage a team's morale during a difficult period.",
    "How do you handle a situation where a client is unhappy with the final product?",
    "Describe a time you had to learn a new programming language or framework.",
    "How do you handle a situation where you are not getting credit for your work?",
    "Tell me about a time you had to work with a team member who had a different work style.",
    "How do you handle a situation where you are facing a lack of communication from a stakeholder?",
    "Describe a time you had to deal with a production issue on a weekend or after hours.",
    "How do you ensure that your team is following the company's best practices?",
    "Tell me about a time you had to convince a team to adopt a new tool or process.",
    "How do you handle a situation where a project is over budget?",
    "Describe a time you had to lead a project from start to finish."
]

    }